# APSC 1001 - CS 1010
# Week 3 - Pandas Deep Dive
    
### Instructor: Dr. Kartik Bulusu, [MAE] 
    
#### Teaching Assistants: name [dept]

#### Learning Assistants: Ethan Frink [MAE], Alexis Renderos [MAE]

Let's start by importing our favorite friends as always going forward in this class: **numpy**, **matplotlib**, and **pandas**

In [ ]:
import numpy as np
from matplotlib import pyplot as plt
import pandas as pd

Before we get started with pandas, we are going to introduce a function called `help()` which will provide some information about functions we are working with!

In [ ]:
#Here we ask python to tell us about the np.array function, but this works with everything!
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly c

Pandas is a library to work with dataframe objects. Dataframes are a way to represent data in rows and columns, much like a matrix!! 

A little vocab to get us started. I promise it won't be much. 
- The **columns** of a dataframe are called the **columns**
- The **rows** of the dataframe are called the **index** 

See that wasn't too bad :)

Last week we discussed importing data from a csv file into a pandas dataframe. We are going to bring that back and do a whole lot more with it this week! We have provided a csv file in this week's content for this demonstration! 



#### Here are the steps!
1. Locate the file titled `DemoCSV1.csv` in the DeepNote file tree (on the left of the screen). You may have to click the `Notebooks and Files` icon on the top left to see this

2. Click the 3 dots. This should bring you to a drop down menu. 

3. Click `Copy Path to Clipboard` from the dropdown menu!

4. Establish a `filename` variable in a code cell that is an empty string using `filename = ''`

5. Inside the quotes paste the path using `Ctrl+V` or `Cmd+V` on your keyboard

6. You should now have something like this: `filename = '/work/Week3/DemoCSV1.csv'`

7. Finally, use `df = pd.read_csv(filename)` to save your file into a pandas dataframe!


Today's `DemoCSV1.csv` originally comes from the module [vega_datasets](https://vega.github.io/vega-datasets/) if you are curious.

In [ ]:
filename = '/work/Fall 2021/for_students/Week3/DemoCSV1.csv'
df = pd.read_csv(filename)

### Showing Dataframes
To show dataframes, we have a couple of options! First we can use what we did last week using the `display(df)` function which operates similarly to `print()`. We can also use `df.head()` and `df.tail()` which will just show parts of the frame. The `.head(n)` shows the first n lines of the frame, and the `.tail(m)` shows the last m lines of the frame

Let's try these out!

In [ ]:
display(df)

Unnamed: 0                       Name  Miles_per_Gallon  Cylinders  \
0             0  chevrolet chevelle malibu              18.0          8   
1             1          buick skylark 320              15.0          8   
2             2         plymouth satellite              18.0          8   
3             3              amc rebel sst              16.0          8   
4             4                ford torino              17.0          8   
..          ...                        ...               ...        ...   
401         401            ford mustang gl              27.0          4   
402         402                  vw pickup              44.0          4   
403         403              dodge rampage              32.0          4   
404         404                ford ranger              28.0          4   
405         405                 chevy s-10              31.0          4   

     Displacement  Horsepower  Weight_in_lbs  Acceleration        Year  Origin  
0           307.0       130.0           3504          12.0  1970-01-01     USA  
1           350.0       165.0           3693          11.5  1970-01-01     USA  
2           318.0       150.0           3436          11.0  1970-01-01     USA  
3           304.0       150.0           3433          12.0  1970-01-01     USA  
4           302.0       140.0           3449          10.5  1970-01-01     USA  
..            ...         ...            ...           ...         ...     ...  
401         140.0        86.0           2790          15.6  1982-01-01     USA  
402          97.0        52.0           2130          24.6  1982-01-01  Europe  
403         135.0        84.0           2295          11.6  1982-01-01     USA  
404         120.0        79.0           2625          18.6  1982-01-01     USA  
405         119.0        82.0           2720          19.4  1982-01-01     USA  

[406 rows x 10 columns]

In [ ]:
df.head(10)

Unnamed: 0                       Name  Miles_per_Gallon  Cylinders  \
0           0  chevrolet chevelle malibu              18.0          8   
1           1          buick skylark 320              15.0          8   
2           2         plymouth satellite              18.0          8   
3           3              amc rebel sst              16.0          8   
4           4                ford torino              17.0          8   
5           5           ford galaxie 500              15.0          8   
6           6           chevrolet impala              14.0          8   
7           7          plymouth fury iii              14.0          8   
8           8           pontiac catalina              14.0          8   
9           9         amc ambassador dpl              15.0          8   

   Displacement  Horsepower  Weight_in_lbs  Acceleration        Year Origin  
0         307.0       130.0           3504          12.0  1970-01-01    USA  
1         350.0       165.0           3693          11.5  1970-01-01    USA  
2         318.0       150.0           3436          11.0  1970-01-01    USA  
3         304.0       150.0           3433          12.0  1970-01-01    USA  
4         302.0       140.0           3449          10.5  1970-01-01    USA  
5         429.0       198.0           4341          10.0  1970-01-01    USA  
6         454.0       220.0           4354           9.0  1970-01-01    USA  
7         440.0       215.0           4312           8.5  1970-01-01    USA  
8         455.0       225.0           4425          10.0  1970-01-01    USA  
9         390.0       190.0           3850           8.5  1970-01-01    USA

In [ ]:
df.tail(10)

Unnamed: 0                        Name  Miles_per_Gallon  Cylinders  \
396         396  chrysler lebaron medallion              26.0          4   
397         397              ford granada l              22.0          6   
398         398            toyota celica gt              32.0          4   
399         399           dodge charger 2.2              36.0          4   
400         400            chevrolet camaro              27.0          4   
401         401             ford mustang gl              27.0          4   
402         402                   vw pickup              44.0          4   
403         403               dodge rampage              32.0          4   
404         404                 ford ranger              28.0          4   
405         405                  chevy s-10              31.0          4   

     Displacement  Horsepower  Weight_in_lbs  Acceleration        Year  Origin  
396         156.0        92.0           2585          14.5  1982-01-01     USA  
397         232.0       112.0           2835          14.7  1982-01-01     USA  
398         144.0        96.0           2665          13.9  1982-01-01   Japan  
399         135.0        84.0           2370          13.0  1982-01-01     USA  
400         151.0        90.0           2950          17.3  1982-01-01     USA  
401         140.0        86.0           2790          15.6  1982-01-01     USA  
402          97.0        52.0           2130          24.6  1982-01-01  Europe  
403         135.0        84.0           2295          11.6  1982-01-01     USA  
404         120.0        79.0           2625          18.6  1982-01-01     USA  
405         119.0        82.0           2720          19.4  1982-01-01     USA

In [ ]:
#Just to showcase it, let's use help(df.tail)
help(df.tail)

Help on method tail in module pandas.core.generic:

tail(n: 'int' = 5) -> 'FrameOrSeries' method of pandas.core.frame.DataFrame instance
    Return the last `n` rows.
    
    This function returns last `n` rows from the object based on
    position. It is useful for quickly verifying data, for example,
    after sorting or appending rows.
    
    For negative values of `n`, this function returns all rows except
    the first `n` rows, equivalent to ``df[n:]``.
    
    Parameters
    ----------
    n : int, default 5
        Number of rows to select.
    
    Returns
    -------
    type of caller
        The last `n` rows of the caller object.
    
    See Also
    --------
    DataFrame.head : The first `n` rows of the caller object.
    
    Examples
    --------
    >>> df = pd.DataFrame({'animal': ['alligator', 'bee', 'falcon', 'lion',
    ...                    'monkey', 'parrot', 'shark', 'whale', 'zebra']})
    >>> df
          animal
    0  alligator
    1        bee
    2  

### Dataframe Shape

An **m** x **n** matrix has **m** rows and **n** columns. A dataframe also has rows and columns! Let's get the shape of the dataframe using `df.shape`

`df.shape` will return the `(number_of_rows, number_of_columns)`

In [ ]:
df.shape

(406, 10)

### Establishing Dataframes
Up until now we have imported a csv file to establish our dataframes. We can also establish frames using numpy arrays --> Think Matrices!! 

To do this we use the `pd.DataFrame(arr)` function which converts our array into a dataframe

Let's make a 3x3 matrix called **A** which is given by the following:

A = $\begin{bmatrix} 1&2&3 \\ -1&-2&-3 \\ 6&5&-5 \end{bmatrix}$

Remember we can use `np.array([[row1],[row2],[row3]])` to create a matrix with 3 rows

In [ ]:
A = np.array([[1, 2, 3], [-1, -2, -3], [6, 5, -5]])
print(A)

[[ 1  2  3]
 [-1 -2 -3]
 [ 6  5 -5]]


Now let's convert that matrix A into a dataframe called `df_A`

Using `pd.DataFrame()` we can convert items to dataframes 

In [ ]:
df_A = pd.DataFrame(A)
display(df_A)

#Let's also print the shape of the dataframe (coming from the 3x3 matrix!)
print(df_A.shape)

0  1  2
0  1  2  3
1 -1 -2 -3
2  6  5 -5

(3, 3)


### Updating Column and Index names

We can name our columns and our rows (or index) to something easier to work with if we'd like. These can be anything at all!

To update the columns, use `df.columns = list_of_names`

To update the rows, use `df.index = list_of_names`


In [ ]:
column_names = ['Col A', 'Col B', 'Col C']
row_names = ['Happy', 'Birthday', 'Everyone!']

df_A.columns = column_names
df_A.index = row_names

display(df_A)

Col A  Col B  Col C
Happy          1      2      3
Birthday      -1     -2     -3
Everyone!      6      5     -5

Notice how all of our data is perserved, we just gave new names to the headers of each!

### Accessing Data within Frames

Using the `df.loc['Row', 'Column']` function we can locate certain data. 

Last week we used this for plotting. We will get to that in a second. Let's pull out the data in column `Col A` and index `Everyone!`

In [ ]:
print(df_A.loc['Everyone!', 'Col A'])

6


Using the colon, `:`, we can pull out slices of information! Last week we pulled the entire column using `df.loc[:,'Column']`

We can just as easily pull the entire row using `df.loc['Row', :]`

We can also pull subsets of the frame. The things in-between specifications using `df.loc['Row1':'Row2', 'Col1':'Col2']`

Let's explore this functionality a bit!

In [ ]:
display(df_A.loc[:, 'Col B'])

Happy        2
Birthday    -2
Everyone!    5
Name: Col B, dtype: int64

In [ ]:
display(df_A.loc['Birthday', :])

Col A   -1
Col B   -2
Col C   -3
Name: Birthday, dtype: int64

In [ ]:
display(df_A.loc[:, 'Col A':'Col B'])

Col A  Col B
Happy          1      2
Birthday      -1     -2
Everyone!      6      5

In [ ]:
display(df_A.loc['Birthday':, 'Col B':'Col C'])

Col B  Col C
Birthday      -2     -3
Everyone!      5     -5

We saw last week the conversion between a slice of a dataframe and a numpy array. To do this we use `slice.values`

For example, to covert a column to a numpy array use `df.loc[:,'Column'].values`

In [ ]:
arr = df_A.loc['Birthday':, 'Col B':'Col C'].values
print(arr)

[[-2 -3]
 [ 5 -5]]


### Updating Values within Frames

You can also change the values of data within the frame using the location! Tell the computer which spot you want to update using and assign the new value:

`df.loc['Row', 'Column'] = value`

**Note:** This is different from `value = df.loc['Row', 'Column']`

In [ ]:
#Let's display df_A again
display(df_A)

Col A  Col B  Col C
Happy          1      2      3
Birthday      -1     -2     -3
Everyone!      6      5     -5

In [ ]:
#Now let's update the value of 5 (in Row 'Everyone!' and Col 'Col B' to a 12)
df_A.loc['Everyone!', 'Col B'] = 12
display(df_A)

Col A  Col B  Col C
Happy          1      2      3
Birthday      -1     -2     -3
Everyone!      6     12     -5

### Pandas Remove NaN Values

Often our data comes with a bunch of missing information. These will fill into our frame as `nan` values. `nan` stands for **Not a Number**. We typically want to get rid of this information!

We can use `pd.dropna(axis=0)` to drop the rows containing `nan` values or `pd.dropna(axis=1)` to drop columns containing `nan`

You can read more about `pd.dropna()` at the documentation [here](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dropna.html)

Let's pull in another csv file, this time from `DemoCSV2.csv` using the same procedure from above! `DemoCSV2.csv` contains some `nan` values and we will process it 

In [ ]:
filename = '/work/Fall 2021/for_students/Week3/DemoCSV2.csv'
df = pd.read_csv(filename)
display(df)

Person          Place  Number
0     Ash           Home     1.0
1   James  Grocery Store     7.0
2  Jessie          Class     NaN
3   Brock            Lab    15.0
4   Misty            NaN    13.0
5    Dawn  Swimming Pool     NaN

In [ ]:
row_drop = df.dropna(axis=0)
display(row_drop)

Person          Place  Number
0    Ash           Home     1.0
1  James  Grocery Store     7.0
3  Brock            Lab    15.0

In [ ]:
col_drop = df.dropna(axis=1)
display(col_drop)

Person
0     Ash
1   James
2  Jessie
3   Brock
4   Misty
5    Dawn

### Saving a DataFrame to a CSV File

This section won't be covered in class, but is good for your reference!

It would be fun but not feel complete if you can pull from a csv but not save to a csv.

Using `df.to_csv(filepath)` you can send a file to path you specify.

The file path is going to be in the form of `folder_path + '/' + name`

The name is up to you, but should end with `.csv`. The `folder_path` can be acquired using the three dots and `Copy path to clipboard` like before but now on the folder instead of the file

In [ ]:
name = 'DemoCSV3.csv'
filepath = '/work/Week3' + '/' + name
row_drop.to_csv(filepath)

## Challenge Question!

Experiment with the `DemoCSV1.csv` file provided! Pick two columns with numerical data, such as the `Miles_per_Gallon` and `Weight_in_lbs` and make a plot. 


Here is an example pseudo-code you might use to accomplish this!
 
```
df1 = pd.read_csv(file)

arr1 = df1.loc[slicing].values
arr2 = df1.loc[slicing].values

plt.plot(arr1, arr2)

```

#### Bonus

For extra challenge plot different correlations on the same graph! 

**Example:**
- `Miles_per_Gallon` vs `Weight_in_lbs` 
- `Horsepower` vs `Weight_in_lbs` 

In [ ]:
#Your code here!

In [ ]:
#If your teammates want to work independently, add more code cells!

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=928a4826-6d7d-44bd-b128-d6cd83127a49' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>